DROP ALL OBJECTS ;

CREATE TABLE IF NOT EXISTS users (
                                     user_id INTEGER    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     login varchar   NOT NULL,
                                     name varchar,
                                     email varchar   NOT NULL,
                                     birthday date   NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
                                   mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   name varchar   NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
                                     film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar   NOT NULL,
                                     description varchar(200)   NOT NULL,
                                     release date   NOT NULL,
                                     duration BIGINT   NOT NULL,
                                     mpa_id INTEGER    REFERENCES mpa(mpa_id)
);


CREATE TABLE IF NOT EXISTS friends (
                                       user_id INTEGER NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
                                       friend_id INTEGER NOT NULL REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS likes (

                                     user_id         INTEGER NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
                                     film_id       INTEGER NOT NULL REFERENCES films (film_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genre (
                                     genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name varchar   NOT NULL
);


CREATE TABLE IF NOT EXISTS film_genre (
                                          film_id INTEGER NOT NULL REFERENCES films (film_id) ON DELETE CASCADE,
                                          genre_id INTEGER    NOT NULL REFERENCES genre(genre_id)
);


